### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Axislmao** [drizzle-mizzle/CharacterAI-Discord-Bot#105]
- [x] I am using the [latest version](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/latest) of the program.
- [x] I have read the [Known-issues](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot#known-issues) section and [Issues](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/issues) page, and made sure that this problem was not already described elsewhere.

idk why it keep showing me the "no power gif" i mean i literally gave it administrator for once, what could be wrong ?🤔

**Comment by drizzle-mizzle** [comment]
If you set `public_mode` to `true` in config, you will need to specify your discord ID in order to execute some commands.
If that's not the case, then you have to re-read the assignments and draw aome conclusion:
https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/issues?q=is%3Aissue+is%3Aclosed+no+power

**Comment by Axislmao** [comment]
THANKS! THAT HELPED HAHA! finally its working lol!
